version: "3"

# `.env.local` takes precedence. Only new keys found in the `.env` will be
# appended to the current set.
dotenv: [".env.local", ".env"]

vars:
  GOLANGCI_LINT_VERSION: v2.11.4
  GOIMPORTS_VERSION: v0.29.0
  DPRINT_VERSION: 0.48.0
  VERSION: # if version is not passed we hack the semver by encoding the commit as pre-release
    sh: echo "${VERSION:-0.0.0-$(git rev-parse --short HEAD)}"

tasks:
  init:
    desc: Setup local env
    deps:
      - install:linter
      - install:goimports
      - install:dprint

  install:linter:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b .bin/ {{ .GOLANGCI_LINT_VERSION }}

  install:goimports:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@{{ .GOIMPORTS_VERSION }}

  install:dprint:
    cmds:
      - curl -fsSL https://dprint.dev/install.sh | sh -s {{ .DPRINT_VERSION }}
      - mkdir -p .bin && cp $HOME/.dprint/bin/dprint .bin/dprint # workaround for local install

  test:
    desc: Run all tests
    cmds:
      - go tool gotest.tools/gotestsum -- -v ./...

  test:cover:
    desc: Run all tests and open cover html report
    cmds:
      - task test -- -coverprofile=coverage.out
      - go tool cover -func=coverage.out
      - go tool cover -html=coverage.out

  lint:
    desc: Run the linters
    cmds:
      - ${PWD}/.bin/golangci-lint run --fix -v --timeout 300s {{ .CLI_ARGS }}

  fmt:
    desc: Run format
    cmds:
      - goimports -l -w .
      - ${PWD}/.bin/dprint fmt

  fmt-check:
    desc: Check format
    cmds:
      - ${PWD}/.bin/dprint check

  build-deb:
    desc: Build debian package using docker
    cmds:
      - docker build --build-arg BINARY_NAME=arduino-linux-config --build-arg DEB_NAME=arduino-linux-config --build-arg VERSION={{ .VERSION }} --build-arg ARCH={{ .ARCH }} --build-arg RELEASE={{ .RELEASE }} --output={{ .OUTPUT }} -f debian/Dockerfile .
    vars:
      ARCH: '{{.ARCH | default "arm64"}}'
      OUTPUT: '{{.OUTPUT | default "./build"}}'

  build:
    desc: "Build the arduino-linux-config locally"
    cmds:
      - go build -v -o ./build/arduino-linux-config ./cmd/arduino-linux-config

  arduino-linux-config:release:
    desc: Create a tag on the current commit and push it to the remote to create the release
    cmds:
      - |
          if [ -z "{{.CLI_ARGS}}" ]; then
            echo "Error: Version argument is required. Usage: task orchestrator:trigger:release -- <version>"
            exit 1
          fi
      - git tag -a "{{.CLI_ARGS}}" -m "Release {{.CLI_ARGS}}"
      - git push origin "{{.CLI_ARGS}}"

  board:install:
    desc: Install arduino-linux-config on the board
    interactive: true
    cmds:
      - rm ./build/*.deb || true
      - task: build-deb
      - adb shell rm /tmp/*.deb || true
      - adb push ./build/arduino-linux-config_*_arm64.deb /tmp/
      - ./scripts/run-remote-sudo.sh "dpkg -i /tmp/arduino-linux-config*_arm64.deb && needrestart -r a"

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:cache-dep-licenses:
    desc: Cache dependency license metadata
    deps:
      - task: general:prepare-deps
    cmds:
      - |
          if
            ! which licensed \
            &>/dev/null
          then
            if [[ {{OS}} == "windows" ]]; then
              echo "Licensed does not have Windows support."
              echo "Please use Linux/macOS or download the dependencies cache from the GitHub Actions workflow artifact."
            else
              echo "licensed not found or not in PATH."
              echo "Please install: https://github.com/licensee/licensed#installation"
            fi
            exit 1
          fi
      - licensed cache
      - licensed notices

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-dependencies-task/Taskfile.yml
  general:check-dep-licenses:
    desc: Check for unapproved dependency licenses
    deps:
      - task: general:cache-dep-licenses
    cmds:
      - |
          MATCHES="$(
            find \
              .licenses \
              -regex '.+\.yml' \
              -type f \
              -print0 \
            | \
              xargs \
                --null \
                go tool \
                  github.com/mikefarah/yq/v4 \
                    'select(.license == "other") | filename'
          )"
          if [[ "$MATCHES" != "" ]]; then
            printf "%s" "$MATCHES"
            echo
            echo "The license cache files above have the license set to 'other'. Please manually define the license type and retry."
            echo "See: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-go-dependencies-task.md#unrecognized-licenses"
            exit 1
          fi
      - licensed status

  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-go-dependencies-task/Taskfile.yml
  general:prepare-deps:
    desc: Prepare project dependencies for license check
    # No preparation is needed for Go module-based projects.
