// This file is part of arduino-linux-config.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

//go:build integration

package integration

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// Device tree generated by the VentunoQ (arduino,monza) board configuration.
const ventunoqGeneratedDtb = "combined-dtb.dtb"

type addonStatusResult struct {
	Name           string `json:"name"`
	CurrentEnabled bool   `json:"current_enabled"`
	NextEnabled    bool   `json:"next_enabled"`
}

type addonsShowResult struct {
	Addons []addonStatusResult `json:"addons"`
}

// Runs a command against the device tree partition, which is mounted only while
// the tool is applying overlays.
func inDtbPartition(t *testing.T, command string) string {
	t.Helper()
	return execInVentunoqContainer(t, "sh", "-c", strings.Join([]string{
		"set -eu",
		"mkdir -p /mnt/dtb",
		"mount -t vfat " + ventunoqDtbPartition + " /mnt/dtb",
		"trap 'umount /mnt/dtb' EXIT",
		command,
	}, "\n"))
}

func generatedDtbMd5(t *testing.T) string {
	t.Helper()
	out := inDtbPartition(t, "md5sum /mnt/dtb/"+ventunoqGeneratedDtb)
	fields := strings.Fields(out)
	require.NotEmpty(t, fields, "unexpected md5sum output: %q", out)
	return fields[0]
}

func addonsShow(t *testing.T) addonsShowResult {
	t.Helper()
	out := execInVentunoqContainer(t, "arduino-linux-config", "addons", "show", "--format", "json")

	var result addonsShowResult
	require.NoError(t, json.Unmarshal([]byte(out), &result), "output should be valid JSON")
	return result
}

func requireAddonNextEnabled(t *testing.T, show addonsShowResult, name string, expected bool) {
	t.Helper()
	for _, addon := range show.Addons {
		if addon.Name == name {
			require.Equal(t, expected, addon.NextEnabled, "unexpected next state for addon %s", name)
			return
		}
	}
	require.Fail(t, "addon not found", name)
}

func TestAddonsGenerateDeviceTree(t *testing.T) {
	startVentunoqDockerContainer(t)
	t.Cleanup(func() { stopVentunoqDockerContainer(t) })

	// Baseline: no addon enabled, the device tree is the one shipped by the board.
	execInVentunoqContainer(t, "arduino-linux-config", "reload")
	baseDeviceTree := generatedDtbMd5(t)

	execInVentunoqContainer(t, "arduino-linux-config", "addons", "enable", "automation")
	automationDeviceTree := generatedDtbMd5(t)
	require.NotEqual(t, baseDeviceTree, automationDeviceTree, "enabling an addon should change the device tree")

	execInVentunoqContainer(t, "arduino-linux-config", "addons", "enable", "audio-codec-zero")
	audioDeviceTree := generatedDtbMd5(t)
	require.NotEqual(t, baseDeviceTree, audioDeviceTree, "enabling an addon should change the device tree")
	require.NotEqual(t, automationDeviceTree, audioDeviceTree, "each addon should generate a different device tree")

	// Only one addon at a time is allowed.
	show := addonsShow(t)
	requireAddonNextEnabled(t, show, "automation", false)
	requireAddonNextEnabled(t, show, "audio-codec-zero", true)

	// Reload re-applies the persisted configuration and regenerates the device tree.
	inDtbPartition(t, "rm /mnt/dtb/"+ventunoqGeneratedDtb)
	execInVentunoqContainer(t, "arduino-linux-config", "reload")
	reloadedDeviceTree := generatedDtbMd5(t)
	require.Equal(t, audioDeviceTree, reloadedDeviceTree, "reload should restore the device tree of the enabled addon")

	execInVentunoqContainer(t, "arduino-linux-config", "addons", "disable")
	disabledDeviceTree := generatedDtbMd5(t)
	require.Equal(t, baseDeviceTree, disabledDeviceTree, "disabling every addon should restore the base device tree")
}
