// This file is part of arduino-linux-config.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

//go:build integration

package integration

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// Device tree generated by the VentunoQ (arduino,monza) board configuration.
const ventunoqGeneratedDtb = "combined-dtb.dtb"

// Runs a command against the device tree partition, which is mounted only while
// the tool is applying overlays.
func inDtbPartition(t *testing.T, command string) string {
	t.Helper()
	return execInVentunoqContainer(t, "sh", "-c", strings.Join([]string{
		"set -eu",
		"mkdir -p /mnt/dtb",
		"mount -t vfat " + ventunoqDtbPartition + " /mnt/dtb",
		"trap 'umount /mnt/dtb' EXIT",
		command,
	}, "\n"))
}

func generatedDtbMd5(t *testing.T) string {
	t.Helper()
	out := inDtbPartition(t, "md5sum /mnt/dtb/"+ventunoqGeneratedDtb)
	fields := strings.Fields(out)
	require.NotEmpty(t, fields, "unexpected md5sum output: %q", out)
	return fields[0]
}

// show prints every mount of the board, so the hat is selected by name.
func requireHatNextEnabled(t *testing.T, name string, expected bool) {
	t.Helper()
	out := execInVentunoqContainer(t, "arduino-linux-config", "hw", "show", "--format", "json")

	var result showResult
	require.NoError(t, json.Unmarshal([]byte(out), &result), "output should be valid JSON")
	for _, mount := range result.Mounts {
		if mount.Name == name {
			require.Equal(t, "hat", mount.Kind, "%s should be a hat", name)
			require.Equal(t, expected, mount.NextEnabled, "unexpected next state for hat %s", name)
			return
		}
	}
	require.Fail(t, "hat not found", name)
}

func TestHatGeneratesDeviceTree(t *testing.T) {
	startVentunoqDockerContainer(t)
	t.Cleanup(func() { stopVentunoqDockerContainer(t) })

	// Baseline: no hat enabled, the device tree is the one shipped by the board.
	execInVentunoqContainer(t, "arduino-linux-config", "reload")
	baseDeviceTree := generatedDtbMd5(t)

	execInVentunoqContainer(t, "arduino-linux-config", "hw", "enable", "automation")
	automationDeviceTree := generatedDtbMd5(t)
	require.NotEqual(t, baseDeviceTree, automationDeviceTree, "enabling a hat should change the device tree")

	execInVentunoqContainer(t, "arduino-linux-config", "hw", "enable", "audio-codec-zero")
	audioDeviceTree := generatedDtbMd5(t)
	require.NotEqual(t, baseDeviceTree, audioDeviceTree, "enabling a hat should change the device tree")
	require.NotEqual(t, automationDeviceTree, audioDeviceTree, "each hat should generate a different device tree")

	// Only one hat at a time is allowed.
	requireHatNextEnabled(t, "automation", false)
	requireHatNextEnabled(t, "audio-codec-zero", true)

	// Reload re-applies the persisted configuration and regenerates the device tree.
	inDtbPartition(t, "rm /mnt/dtb/"+ventunoqGeneratedDtb)
	execInVentunoqContainer(t, "arduino-linux-config", "reload")
	reloadedDeviceTree := generatedDtbMd5(t)
	require.Equal(t, audioDeviceTree, reloadedDeviceTree, "reload should restore the device tree of the enabled hat")

	execInVentunoqContainer(t, "arduino-linux-config", "hw", "disable")
	disabledDeviceTree := generatedDtbMd5(t)
	require.Equal(t, baseDeviceTree, disabledDeviceTree, "disabling every hat should restore the base device tree")
}
