// This file is part of arduino-linux-config.
//
// SPDX-FileCopyrightText: Arduino s.r.l. and/or its affiliated companies
// SPDX-License-Identifier: GPL-3.0-or-later

//go:build integration

package integration

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// Device tree generated by the UnoQ (arduino,imola) board configuration.
const unoqGeneratedDtb = "/boot/efi/dtb/qcom/qrb2210-arduino-imola.dtb"

func md5InContainer(t *testing.T, path string) string {
	t.Helper()
	out := execInContainer(t, "md5sum", path)
	fields := strings.Fields(out)
	require.NotEmpty(t, fields, "unexpected md5sum output: %q", out)
	return fields[0]
}

func TestReloadRestoresGeneratedDeviceTree(t *testing.T) {
	startDockerContainer(t)
	t.Cleanup(func() { stopDockerContainer(t) })

	// Enable the panel: the device tree must be regenerated with the panel overlay, this is the expectedDeviceTree
	execInContainer(t, "arduino-linux-config", "carrier", "enable", "media-carrier", "display=8-dsi-touch-a")
	expectedDeviceTree := md5InContainer(t, unoqGeneratedDtb)

	// Corrupt the generated device tree.
	execInContainer(t, "sh", "-c", "printf '\\xde\\xad\\xbe\\xef!!!' >> "+unoqGeneratedDtb)
	corruptedDeviceTree := md5InContainer(t, unoqGeneratedDtb)
	require.NotEqual(t, expectedDeviceTree, corruptedDeviceTree, "corrupting the device tree should change its checksum")

	// Reload re-applies the persisted configuration and regenerates the device tree.
	execInContainer(t, "arduino-linux-config", "reload")
	displayDeviceTree := md5InContainer(t, unoqGeneratedDtb)
	require.Equal(t, displayDeviceTree, expectedDeviceTree, "reload should restore the device tree generated by the persisted configuration")
}

type reloadResult struct {
	BoardID          string   `json:"board_id"`
	DryRun           bool     `json:"dry_run"`
	ReloadedCarriers []string `json:"reloaded_carriers"`
	ReloadedAddons   []string `json:"reloaded_addons"`
}

func TestReloadWithEmptyStatus(t *testing.T) {
	startDockerContainer(t)
	t.Cleanup(func() { stopDockerContainer(t) })

	// A freshly installed system has no persisted status files.
	statusDir := execInContainer(t, "ls", "-A", "/var/lib/arduino-linux-config/status")
	require.Empty(t, strings.TrimSpace(statusDir), "status directory should be empty on a fresh install")

	out := execInContainer(t, "arduino-linux-config", "reload", "--format", "json")

	var result reloadResult
	err := json.Unmarshal([]byte(out), &result)
	require.NoError(t, err, "output should be valid JSON")

	require.False(t, result.DryRun)
	require.Empty(t, result.ReloadedCarriers)

	// Reload must not persist any status file: it only re-applies the current configuration.
	statusDirAfter := execInContainer(t, "ls", "-A", "/var/lib/arduino-linux-config/status")
	require.Empty(t, strings.TrimSpace(statusDirAfter), "reload should not create status files when none existed")
}
