name: Release arduino-linux-config

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.ARDUINOBOT_TOKEN }}
  GITHUB_USERNAME: ArduinoBot

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Set env vars
        run: |
          echo "TAG_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "creating tag ${TAG_VERSION}"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git for private repo cloning
        run: |
          git config --global url."https://${{ env.GITHUB_USERNAME }}:${{ env.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build deb
        run: |
          go tool task build-deb VERSION=${TAG_VERSION} ARCH=arm64 RELEASE="true"

      - name: Create Github Release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          artifacts: build/*.deb
          allowUpdates: true
